---
title: "A summer of sprinting"
subtitle: "Exploring a new discipline"
date: "`r Sys.Date()`"
output:
    tufte::tufte_html: default
---

```{r setup, include=FALSE}
library(tufte)
knitr::opts_chunk$set(tidy = FALSE, cache.extra = packageVersion('tufte'))
options(htmltools.dir.version = FALSE)
home <- Sys.getenv("HOME")
```

I can no longer escape the conclusion that I have now taken up sprinting as a hobby. How did that happen? Is that even a thing? Trying to figure out how it happened is an interesting exercise in memory and analysis, because it is not easy to understand how it _actually happened_. I can (and will) tell about how I spent the last four months researching and practicing sprint technique and training methods, but that doesn't answer the question of how I came to do that, and why I want to continue doing it.

# Proximal origins

How one gets into a new hobby is often a case of one thing leads to another, and this is probably true of my sprinting exploration too. There are many factors at work, some in sequence, some simultaneously. The most likely catalyst is the fact that my eldest son has been doing athletics for the last 3 years. The other factor, which acts in combination with the aforementioned is that the track where they practice athletics is very close to home. The track, which is standard tartan, has 5 lanes, a 60m straight and ~200m oval, and happens to be open to the public at all times. It is also colocated with a small football field, outdoor gym, and sits in a park area where lots of people go running, walking, and just hang out. All in all it is a great place to be with kids, and so I made it into a usual destination for me and the boys.

So I naturally started spending more time at the track. Not liking to sit still, and wanting to join the boys in their running, it was also natural to sprint with them for fun. In May sometime one of the other dads was there one day and asked if we wanted to race with his kid, just for fun. I decided to run as fast as I could just for the hell of it, and managed the 60m in ~8.6 seconds - not amazing, but not utterly terrible either. Most of all it felt good to try hard.

Other recent trends in my life contributed to me liking it. About a year and a half ago I decided to try out deadlifting and the olympic lifts as part of my mission to climb harder (I'll write more about my weightlifting explorations in a future post). I had also been doing more cross-country skiing so my legs were feeling more awake. It felt good to use the strength in my legs. At the same time my friend Jurie had been exploring plyometrics for developing and using explosive jump strength in climbing, so following his lead I was gradually looking into that too. It is quite fun to jump high and far with maximal effort, so even if one didn't aim to apply those skills in climbing it is motivating to work with. All in all I was more tuned in to my legs as an engine for movement, so the sprinting exploration was quite simply serendipitous.

One last seemingly paradoxical factor is the fact that I had started teaching regular yoga classes this year. How can that be related to exploring sprinting? A big part of designing yoga sequences that are suitable for others is relating to the types of movements that they typically do and the movements that they can do. In practice that means that my own way of practicing, which is quite heavy on arm-balance, does not really fit most people. It is seldom that people who pitch up for drop-in yoga classes spend time on their arms in handstands, L-sits, planche progressions and the like (I wish it were otherwise but oh well). Most people relate more to their legs for balance and strength. So it made sense for me to direct my attention to the legs and hips, their anatomy, and their functional ranges when designing yoga sequences for others. And in this sense it was very interesting to explore a domain of movement such as sprinting in which the legs and hips are of central importance. It was an amazing opportunity to learn. Exploring sprinting has enabled me to improve my functional anatomical knowledge, which allows me to design better yoga sequences for myself and others.

# Distant origins

It is amazing how movement can trigger the recollection of memories that seemed lost and/or irrelevant before. When thinking about the movement of sprinting I was reminded of all the running I did as a child. In primary school we had an athletics day twice a year, where all of the kids did sprints, hurdles, long jump, high jump, and a 1500m _I think_. All of it barefoot on the grass, and sometimes we had inter-school races at a proper stadium and track. I remember my brother and I had a game where we would try to race against cars driving past our house. After dinner we'd go out onto the sidewalk, wait until the cars reach a certain point and then sprint at top speed back to our driveway, the aim being to get there before the car. Timeless entertainment!

Probably the most significant running domain during my childhood was rugby. In South Africa at that time, it was normal (maybe even compulsory) for _all_ boys to play rugby for the whole of primary school (grades 1 - 7). I laugh out loud now when I think about it. How crazy it was to have all these small boys tackling each other on the field. It was never my favourite sport, and I was happy to stop playing once I went to high school, but looking back I probably developed some decent physical foundations for running there. In high school I was fully consumed by all forms of cycling, and after school by climbing and skydiving so any form of sprinting was essentially dormant from age 13 until 42.

# Investigating the craft

So it was against this backdrop that I posed myself the question this summer: can I get faster at sprinting? Even more fundamentally, can I sprint at all? This might sound like an absurd question to pose, but the thing is that sprinting is not the same as running fast. In order to try and sprint faster I had to figure out how sprinting works, and how people go about improving the practice. One of the first things I figured out, by watching a video by Stuart McMillan, was that sprint technique is fundamentally different from intuitive running: the emphasis on using the front of the body, bringing the knees high up before foot strike, landing on the front of the foot - all of these things are impossible to sustain for longer periods of time while running, and do not really emerge naturally when transitioning from a slow run to a faster pace.

With some visual cues and movement patterns in mind I set about doing 60m sprints at the track whenever I was hanging out there with the boys. The first task was just testing the movement to see if I could run at top speed without getting hurt or being too sore for my own liking. I hadn't done this for a good 29 years so there were many unknowns. After doing this for a while I needed some visual feedback on how I was moving, in addition to referring to my own experience while doing so. So I started filming my sprints to see what was going on. Soon it was summer holiday so I had plenty of time for experiments and investigations.

Seeing myself sprint from the front and from the side was very revealing and helped me generate many questions. Was my arm movement correct? Was I upright enough? Were my knees high enough? What should I do with my knees during the start? How should one even start? Why was I turning my right foot slightly outward before striking the ground? Why was my shoulder doing a small external rotation at the very back of the arm swing? Is that a bad thing? Why do I rock from side to side while at top speed? Should I swing my arms less? Should I tense my upper body more for stability? Am I striking with the front of my feet? Are my heels banging into the ground? Are my running shoes holding me back?

I was able to answer some of these questions by referring to the knowledge I have of my own body. For example, that my right hip is more flexible than my left, and that my left leg and right arm are stronger than their opposites. Other questions I had to investigate by finding articles and/or videos online, or by watching other professional sprinters run. Both of these approaches have their merits but are necessarily limited when working alone as a novice experimenter. Anyways, I eventually managed to gather enough knowledge to carve out a basic routine for myself, including warm-up and sprint technique drills. I also figured out that many sprint programs use the power clean (a variation of the clean and jerk olympic lift) and squat variations to develop relevant explosive power and strength. So I added those along with the plyometrics and sprint drills to my loose program.

After a while I was curious to see if any of it was working and so I figured out how to roughly time myself using the videos. At the end of July I was hitting 8.0 seconds on the 60m. Still not amazing, but I _was_ getting faster and having fun trying.

# Mental barriers

As the holiday was coming to an end I needed to assess whether I would call it a day with sprinting. Should I take the lessons and practices I learnt and use that as driving factors for other physical pursuits or do I want to try and cultivate the practice of sprinting in its own right?

Even before I reached the point where I had to make this decision I faced so many small internal mental barriers. If this sounds absurd or unfamiliar then go outside and do some skips. Just skip around for about 5 minutes. I guarantee you that it will feel awkward, even though skipping is something that almost everyone does as a child. It might even feel so awkward that you cannot get yourself to do it without laughing. This is of course even more pronounced if others can see you doing it. Then you have to deal with the thoughts about what other people think. Why is this 42 year old man skipping around? Does he think he is 6 years old? Why is he moving so playfully?

The thing is, sprint drills and sprinting itself _is playful_. It is extremely expressive. If you want to sprint fast you have to cultivate the ability to move in a playful way while deliberately expressing all of the power you have. If you actully do this, then you are very much on display. You cannot play it cool or hide anything if you are actually giving it all you have. Exposing your honest efforts to strangers like this can be difficult, especially if it is not a discipline which you have mastered. You have to deal with your own perception of their perception of you. I have none of these anxieties when I climb because I have a pretty decent level, and I know I move well, but when you're a beginner out in the public space it is suddenly very different.

Many other questions popped up in my head: am I good enough to do this without looking like a fool? Isn't it ridiculous for a 42 year old man to _start_ sprinting? What on earth can I accomplish by putting energy into this, objectively speaking? Another difficulty is the story. How do I tell other people what I am doing here. Do I tell them that I am investigating functional anatomy through sprinting in order to apply it to my yoga teaching? Not that there is anything wrong with that but let's just say it is not the most normal thing to do, so I find it hard to get myself to say something like that.

In the end I decided to take inspiration from my children who fearlessly try new things and do everything without concerns about identity, accomplishment, or social validation. I decided I would set aside my ridiculous social anxieties, not worry about the story and stick with my gut feeling that I should continue exploring this discipline and try to practice it to the best of my ability.

# Learning from others

One of the best ways to advance in a movement discipline is to get instruction from someone who has mastered it. By the end of July I had reached the point where it was difficult to answer some of the remaining questions I had without the viewpoints of a professional. After searching for various options I found a [Norwegian company](https://elitesprinttrening.no/) that does sprint training. Broadly speaking my aim was to get insight into how I should move, and how I can get there. I opted for four individual sessions focusing on: starting (including using starting blocks), acceleration, top speed, and technique.

Over the course of the four sessions I gained a better understanding of sprint drills, training explosiveness, how sprint training sessions are structured, and of course how to sprint! Learning to use starting blocks was a challenge in itself - how to coordinate the explosive start without stumbling. Practicing acceleration from the start was perhaps the most revealing of the different topics, as top speed (upright sprinting technique) was intuitively easier to grasp. The difficult thing is to sprint with frontside mechanics from the very start throughout the acceleration phase into top speed.

What is difficult about the movement during acceleration is that you have to try and move the trailing foot back into the driving position close to the ground, almost as if you are dragging your feet, and then drive the foot down and back into the ground just behind your hips. When sprinting upright at top speed the foot comes up from the ground as it moves forward with knee-drive. The temptation is to emulate this movement in acceleration too. Instead one should emphasise using the front of the body throughout, pulling the feet forward as soon as they're off the ground. The main difference is that you are leaning forward during acceleration. You can get a feel for this by jumping forward on one leg, close to the ground, and snapping the jumping leg forward as fast as possible as soon as you are done pushing into the ground. You should feel the entire frontside of the body working to accomplish just that.

It was also very helpful to have the opportunity to discuss sprinting with a professional sprinter in order to get insights into how they view and practice their craft. And then of course getting specific feedback on your own movements, and cues for how to correct them. The trainer also helped me find spikes which I tried in the last session. Sprinting with spikes is an amazing sensation - it's easier to land and stay on the front of the foot, you have so much more traction and energy return, and it sounds more quiet when moving. I am extremely glad and grateful that I was able to have these four sessions. I was able to learn so much that I wouldn't have discovered on my own.

So did it work? Did the lesson have an effect? Yesterday I ran a 60m in 7.5 seconds, so yes, the lessons worked extremely well! For the 42 year old age group that is actually not bad. I am able to move better and therefore sprint faster. I can now practice the craft more correctly, and enjoy sprinting even more.

# Advantages

In the same way that I approach sprinting with mental barriers that need to be overcome, I luckily also approach it with physical and mental advantages which help me along. For one thing I am stronger, more flexible, and can move better than 10 years ago. My movement repertoire is much larger thanks to the variety of sports I've practiced over the years. I've cleaned up my food and information diet (more about the latter in a future post) so I have plenty of resources to direct towards learning and training.

It is quite unexpected but I think that my 20 years of yoga is greatly beneficial to this sprinting pursuit. Being flexible (while being strong) is helpful since it gives you the ability to create mechanical advantage when applying muscular force. That is, by moving your body in a strategic way you are able to generate more force with a given capacity. In this case, I can get my front knee up fast and the foot forward without being limited by hamstring mobility on the same leg, or quad mobility on the opposite leg. I also get a good toe-off, having good plantar flexion on the foot/ankle. More generally my connective tissue is in good shape due to the variety of movement I get through yoga. This helps for recovery and force production in full-body functional movement. I am also able to train proprioception in yoga: awareness of the body in space. This is helpful in all forms of movement - being able to sense your current position, anticipate the next, and engage neural force correctly.

Bouldering shares the anaerobic component with sprinting, where you use strength and power for intense movements in brief durations. In cross-country skiing I can develop timing, rhythm, and balance with leg and arm movements, even though the technique is slower and more focused on the back of the body.

Perhaps the biggest advantage is that I've had enough time and done enough things to develop the meta-skill of learning how to learn, and how to try hard without being too attached to the outcome. It is satisfying to approach sprinting systematically and to focus on sustainability from the outset.

# Next steps

Now I need to figure out what I want to do with the skill. My tentative plans are to see how I can train with other sprinters (by making friends and/or joining an athletics club), to build up to doing 100m sprints, to participate in some competitions next year to check out that part of the scene, and most of all to continue enjoying the movement and try to get faster!
