
---
title: "Dietary experiments"
subtitle: "Reflections on food, perception and contentment"
date: "`r Sys.Date()`"
output:
    tufte::tufte_html: default
---

```{r setup, include=FALSE}
library(tufte)
knitr::opts_chunk$set(tidy = FALSE, cache.extra = packageVersion('tufte'))
options(htmltools.dir.version = FALSE)
home <- Sys.getenv("HOME")
```

I've always been a fussy eater with strong (and perhaps irrational) aesthetic preferences, but for the most part of my life I ate many different animals, animal products, sweets, snacks, and drank alchoholic drinks once allowed. Since about 2014 I've gradually become more conscious about what I eat and drink, and why, and in recent years have made some more radical changes. Here I reflect on the journey thus far.

# Beginnings

Back in 2014 we (the household of two at that time) decided to stop eating pork, only buy organic chicken, cut down on the amount of red meat, and explore more vegetarian food. This was motivated by a concern for animal welfare in modern industrial agriculture and was accompanied by a wish to explore more Indian and Italian cuisine - the two household favourites.

I also became more aware of the cumulative effects of moderate but habitual alchohol consumption: if you have 6 beers a week (let's say one during the week, 3 on Friday and 2 on Saturday) for a year, for ten years... then you've had 3120 beers. And if one beer is ~400ml, that would be 1248 liters of beer processed by your body. Ouch. So I started reducing the amount of beers that I drank too.

The initial push to eat more consciously and drink more moderately was reinforced by my effort to improve my climbing at the time. I was training mobility, strength, power, and endurance 4 days a week and my body yearned for nutrition and restitution.

In 2015 I developed an annoying case of climbing related elbow tendonosis. This prompted me to experiment with following a vegetarian diet in order to try and reduce inflammation in the body (I don't think there is any strong empirical support for treating tendonosis with a vegetarian diet, but I was willing to try anyways). At the time I didn't have the motivation, knowledge, or discipline to follow through completely, but the intitial explorations allowed me to learn some new cooking skills which would come in handy later.

# Vegan

In 2020 I made a new friend who happened to be a long-time vegetarian, who had recently "gone vegan". I was impressed by how good the dishes were that he prepared, and found the vegan food products a bit interesting. It was also the time of lockdowns in the Covid-19 pandemic, so I was eager to have new experiences given the general lack of options. On his recommendation I watched [a documentary film about plant-based food](https://gamechangersmovie.com/food/core-principles/) which showed how athletes can change their diet to be more plant-based while still meeting their nutritional needs.

So in the summer of 2021 I took the plunge and tried to eat vegetarian. Once I had success with that I gradually tried eating vegan. From the outset I decided that I wouldn't think of this experiment as a change in identity, and that I would adopt this way of eating for myself in a non-fundamentalist way. That is, I am not trying to get anyone's approval by eating in a specific way, nor am I trying to conform to some approved vegan standard. And by not building an elaborate identity around it I remain free to change it without fear of invoking my own or someone else's scorn. The point of this change was not to add any anxiety to the act of eating, but rather to develop a more conscious and ethical way of eating, in a joyfull way.

I was also motivated by a concern for animal welfare, and to a lesser degree the climate impact of my eating. I don't believe that it is unethical to eat animals _per se_, or that I will never eat animals again. I just think that the global industrial argicultural complex has created animal-based food production that creates a whole mass of suffering for the animals in question. I can certainly entertain the idea of catching a fish, or hunting a deer and eating it. In that case it will have lived a decent life. But the factories that turn pigs, chickens, and cows into meat do not typically prioritise the welfare of these animals, and as a supermarket consumer I have no way of checking the nature of the value chains involved in delivering the meat products. The easiest solution is therefore to just opt out.

Beyond the ethical concerns I found it exciting to be forced into learning more about food, cooking and nutrition. Eating vegan in a sustainable way requires knowledge, skill, and motivation. First of all you need knowledge of ingredients and nutrition, and skill in food preparation. You need to know what can you eat in order to meet your nutritional needs, and you need to know how to create satisfactory meals from these ingredients. In researching the nutritional value of ingredients I finally learned about [essential amino acids](https://en.wikipedia.org/wiki/Essential_amino_acid) - organic compounds present in proteins that cannot be synthesised by the human body, and that need to be ingested via food. Beyond having to refresh my knowledge of legumes and nuts, it also led me to discover the magic of seeds (pumpkin, sunflower, sesame, flax, hemp, amaranth, nettle), and the world of algae (such as spirulina) and fungi.

More subtle and perhaps more difficult skills extend to social interactions: being able to say no thanks in ways that do not upset ongoing conversations, and that do not draw out unnecessary discussions about ways of eating; being able to eat out at a restaurant with others, and be content with ordering fries while everyone else has a proper meal; or just being agreeable while being hungry because people might not have any vegan alternatives to serve.

# Simplifications

Adopting a more or less vegan diet forced me to be more aware of what I eat, and to exert more self-control over food in general. With so much food on offer from all sides (the reality of living in Oslo, Norway) at so many occassions, a big part of vegan eating boils down to abstinance, or eventually abandonment - basically, repeatedly saying no. The whole process of eating therefore becomes a laboratory for self-control, where you can observe the formation of urges and desires, and practice abandoning them in favour of other things, or nothing at all. After a while you stop wanting to eat what you previously automatically wanted. It is documented that what you eat has a profound influence on how you feel and think via gut-brain pathways - elaborated on by [this paper on the Regulation of Neurotransmitters by the Gut Microbiota and Effects on Cognition in Neurological Disorders](https://pmc.ncbi.nlm.nih.gov/articles/PMC8234057/). My working theory about dealing with such radical dietary changes is that it takes time for your gut bacteria and the resulting cognition to change, for your more raw perceptions to change, and for you to change the stories you tell yourself and others about why you are doing things. We tend to maintain and update such stories in our own minds, and often attempt to influence the stories we think others tell themselves about us.

The renewed awareness and control resulted in a natural review of the rest of my dietary habits, which brought me to investigate my consumption of sweets, snacks, sodas, and alcohol. At first I decided to experiment with cutting out chocolate completely. When I saw that I could do that I excluded all sweets, and sodas. Then I excluded potato chips, keeping salted nuts and occasional popcorn available on the menu. In parallel I reduced my alcohol consumption to almost zero. I still drink coffee.

A part of my initial hesitance to try and exclude these items from my diet was a worry that somehow my happiness relied on it, and that I would be unhappy if I did - not _ultimately unhappy_, but I wondered whether I would be dissatisfied with my daily life. I also wondered how I would explain these decisions to others. I think this worry underpins many of our hesitations when we want to make changes to our lives. The experiences we regularly have become a part of our identities, a part of what we feel to be ourselves, and what we think others think. And the thought of no longer having those experiences feel like a great loss. What we need in such circumstances is to trust ourselves that we are able to create happiness in our new situations, and this requires practice. The more we make such changes, the better we get at it, and the more clearly we see that we do not in fact need so many circumstantial experiences to be content, or to be "ourselves". The flip-side of this observation is that we have a tendency to accumulate unnecessary behaviours that do not actually make meaningful contributions to our happiness. This is true for what we eat, but also holds true for other aspects of life (it is easy to extrapolate this to the digital realm, for example).

At worst, the unnecessary behaviours we accumulate can [harm ourselves](https://www.nature.com/articles/s41591-024-03345-4) (and others), especially when taken to extremes. In the context of food, much of the time the effects lie in more of a gray area: we spend money (which means we have to work more to make that money), we "spend" taste and attention that could have been directed at other things, and we might be implicitly supporting problematic economic value chains. Individually, the items which fall into the gray area seem insignificant, but many of them combined, and sustained over many years can lead to what is effectively a completely different life.

The positive aspects of cutting out these unnecessary ingredients have been many: I spend less money, I worry less about getting more of this and that, I enjoy food more, and my body composition is more athletic than before. It is amazing how excellent fruit and berries taste when you haven't had sweets in a year. In a more subtle way, having a restrictive diet provides motivation for getting more satisfaction from other parts of life, in addition to providing satisfaction in its own right by way of asserting control over your own body. Since you no longer get small and constant dopamine kicks from snacks, you are forced to search for excitement elsewehere. Instead of being swept along by an ocean of arbitrary impulses, you can take a deep breath, stand apart, and apply that unrealised intent on something that really matters to you.

# Finding food

All of these dietary experiments of mine are happening in a very specific context. Earlier in the text I mentioned that I live in Oslo, and referred to myself as a supermarket consumer. I have a full-time job at the University of Oslo, have two children, and live in an apartment which I own via a mortgage with a Bank. In this mode of living, we are "naturally" led to be (primarily) supermarket consumers when finding food. I say "naturally" to emphasise that there is nothing inherently _natural_ about this way of living. At the same time, this particular combination of things doesn't leave you with a world of time for gathering and growing food yourself, hence: supermarket consumer. In that mode of living, decisions about what you eat often reduce to decisions about what you will purchase (save for when others offer you food which they found by some means). But it is not impossible to go beyond that role, and to get involved in other ways of finding food.

Gardening is one obvious way to obtain food more directly. Find space, buy seeds, prepare the soil, sow the seeds, water if needed, wait, and reap the rewards. We've taken to gardening in two ways: maintaining our own little plot next to the apartment, and participating in a [communal garden](https://www.voksenenga.no/). It is immensely satisfying to be involved with the entire process of growing your own food, and it creates a natural impetus for learning more.

The other less common way to go beyond the role of supermarket consumer is to forage - for plants, fungi (mushrooms) and algae (such as seaweed). Norway has a rich diversity of edible plants, and mushrooms, located in forests and spread around urban growth areas such as parks. Furthermore, the coastline gives access to many edible seaweeds. Thankfully, the foraging scene is also [well organised](https://soppognyttevekster.no/) so that one can learn how to practice it safely (avoiding poisoning) and sustainably (avoiding overuse).

Getting involved in forgaging has been one of the most transformative experiences of my life. In the same way that learning to read transforms a page of shapes into a text that can be understood, knowledge of edible plants and mushrooms changes your view of forests and urban growth from "plants which have shapes and colours" to a world of ingredients, each with their own nuances. It also provides you with a natural connection to the seasons and local geography: you need to know where to be, and when to be there to find your prize.

When you forage you begin to understand that this way of finding food is a perfect fit with the psychological reward mechanisms that we have acquired through evolution (and that are now being exploited by market forces) - the thrill of finding aesthetically pleasing and useful things in unexpected places at unexpected times. And because it transforms your perception of plants, it does the same with your perception of space: what used to be defined as a weed is suddenly useful, seemingly useless spaces become potential foraging grounds. And it gives you access to unique experiences that cannot be bought.

Foraging teaches you about the origins of food, and gives you the opportunity to participate in one of the oldest ways of being human. In fact, it shows you the origin of civilisation - the physical world we've built around us. Everything we have - cars, houses, tools, technology - _everything_ comes from nature. Where else would it come from?

# Preparing food

Using produce from the garden, or bounty from foraging encourages you to be adaptable in your cooking, and in the same breath to consider different methods for food preservation. When you're standing in an aisle you choose want you want based on what you plan to cook. Gardening allows a certain measure of planning, but when your produce ripens it is time to use it. Even more so with foraging, where you have to be opportunistic about what you find. So you have to think on your feet when considering using fresh plants and fungi obtained through gardening and foraging. Or you have too look to preservation: freezing, drying, pickling, fermenting. And then you discover how preservation is intertwined with preparation. Taken together, all of this results in spending more time with raw ingredients, and thiniking more about what you eat.

# Society

I've referred to my current diet as _restrictive_ because implementing it requires the constant exclusion of other options. But it is by no means restrictive in an absolute sense. I am lucky enough to have access to, and the ability to afford, incredible food - imported from all over the world, grown and distributed in Norway, grown in our garden, and foraged from nature around me. The majority of my nutrition comes from imported food (the garden and nature is a bonus), so it would be inconsistent of me to launch into an unconsidered negative rant about the structures of society and food. At the same time, there is much to be dissatisfied with about the structure of society and food - things that become more obvious when you adopt such a restrictive diet, because you repeatedly _see_ what you exclude, and initiate, sustain, and experience the exclusion.

Walking into a supermarket, you see how much floor space is devoted to meat, dairy, sodas, sweets, and snacks. Of course you also see this if you don't exclude it, but it is even more in your face when you see it, experience it's psychological gravity, and walk past it. The market economy, for all of its goods and bads, creates a situation where sellers can be opportunistic about their products. And this opportunism, even without covert malice, leads to the proliferation of food products that are bad for animal welfore, the environment, and for the well-being of those who consume them. There is an entire sales and marketing industry organised around making people buy more sodas, sweets, and snacks. And this industry, staffed as they are with people trained in human psychology, exploits individual psychological weaknesses and circumstantial psychological disadvantages to get people to spend more money on their products - hundreds of shiny, colourful things placed at the height where children see, close to the checkout counters...

Non-beneficial, unconscious, and excessive eating is built into society in more subtle ways. For every left-over religious holiday or celebration there is an accompanying heap of sugary baked goods that are traditionally consumed, coupled with massive lunches and dinners. Maybe it used to make sense some hundreds of years ago to have feasts for these occasions, but in the society I live in, every meal is a feast by past standards.

# Reflections

[Exaptation](https://en.wikipedia.org/wiki/Exaptation) - _the shift in the function of a trait during evolution_.

In the absence of needing to apply the mind and the body to the solution of basic needs, in the absence of reaping the rewards associated with doing so, a flood of random food products promise satisfaction but fail to deliver anything else than transitory and addictive impulses, and questionable nutrition. The traits that make motivated foragers are exapted by the market and turned into utility- and profit-maximising control mechanisms. There is no contentment in all this excess.
