---
title: "Reading the Sutta Pitaka"
subtitle: "The Digha Nikaya and the Majjhima Nikaya"
date: "`r Sys.Date()`"
output:
    tufte::tufte_html: default
---

```{r setup, include=FALSE}
library(tufte)
# invalidate cache when the tufte version changes
knitr::opts_chunk$set(tidy = FALSE, cache.extra = packageVersion('tufte'))
options(htmltools.dir.version = FALSE)
home <- Sys.getenv("HOME")
```

A couple of years ago I had planned on writing about my previous big reading project: Andrew Tanenbaum's computer science books (about computer networking, distributed systems, operating systems, and computer architecture). I never came around to writing about it, and now the whole experience is too far in the past for me to really capture what I wanted to. I want to avoid making the same mistake with my current big reading project: the Sutta Pitaka of the Pali Canon. So instead of waiting until I've finished it before writing about it, I'll rather write this post in several installments, while the material is still fresh enough in my mind.

# The origins of the project

My first encounter with Buddhism was through the work of Breyten Breytenbach in 2001, deceased South African writer, poet, and painter. After that I encountered more through the work of Karen Armstrong, Herman Hesse's Siddhartha, and a movie called Spring, Summer, Fall, Winter... and Spring. In 2007 I read a primary Buddhist text for the first time when I bought myself a copy of the Dhammapadda.

I remember, when reading the Dhammapadda back in 2007, how different the ideas felt - almost as if I couldn't touch them. The ideas were extremely unfamiliar. It's almost like seeing something that you're unable to identify: you turn it this way and that way, but no matter what, you just cannot relate it to anything else you've ever seen. Nevertheless, the Dhammapadda is a beautiful text, and many of the passages are inspiring even without any technical knowledge, and so I re-read it many times in the coming years.

I've [written about](https://leonomics.com/twenty-years-of-yoga.html) how the 2020 pandemic and having a second child messed with my happiness formula, how this was a catalyst for renewing my own yoga practice, and how that involved restarting my reading of Buddhist literature. I wanted to re-investigate the philosophical foundations of my existential reality, because it plays an important part in my happiness. It is perhaps more accurate to say that the terminology I use to describe my experience, my existential reality, is _absolutely crucial_ to my own happiness.

I remembered my previous encounters with Buddhism, and knew that I had never given it proper consideration, other than by reading other people's considerations. Plus, among all the things I had tried to support my own happiness I had never tried meditation. At first I started reading a book about Buddhist meditation but I quickly realised that this too was another person's considerations of Buddhism. If I was going to change the terminilogy of my existence I had to see and decide for myself. The copy of the Dhammapadda I owned was translated by Glenn Wallis, so I ordered another selection of Buddhist discourses translated by him. From here I started having a look at the Pali Canon and decided that it would be best to read the Sutta Pitaka myself.

Why the Sutta Pitaka? The Pali Canon is the set of authoritative texts of the Theravada school of Buddhism. Theravada is older than Mahayana (and Vajrayana), and therefore represents early Buddhism is an accurate way. By extension it is probably a good representation of "what the Buddha said". The Pali Canon consists of three sections: 1) the Vinaya Pitaka (monastic rules), 2) the Sutta Pitaka (the teachings), and 3) the Abdhidamma (more elaborate philosophy). Since I do not aim to become a monk or a specialist in Theravada philosophy I decided that the teachings would be most relevant to explore.

Why explore Buddhism when my aim is to establish robust happiness in my own life? This may sound like a very primitive assessment of Buddhism, but be that as it may: their vision of "the good life" is essentially one in which you "own nothing" and "do nothing" (of course you're not literally _doing nothing_, but nothing conventional, or nothing conventionally). And how is it possible to be happy (content, satisfied, stimulated, engaged, excited, energetic) when you own nothing and do nothing? If you're really capable of that, then you must have a powerful mind. Given this, it stands to reason that Buddhism has developed powerful mental tools for happiness. My aim is to search the writings of the Sutta Pitaka to find these mental tools. To see how they have been constructed, and to construct and adopt the ones that I can usefully apply in my own life. I am working on establishing a mediation practice in a similar way to what I did with yoga, and on evolving the quality of how I reflect on my life.

# Digha Nikaya - The Long Discourses

Whatever text one reads, one does so with expectations. My expectations were shaped by my previous encounters with Buddhism - both through others' texts about it, and through the translations of canonical texts which I had read before. Right or wrong, one of the perceptions that I had going into reading the Digha Nikaya, was that Buddhism is a more empirical religion than most, if not all others. Empirical in the sense that every participant/practitioner is invited to verify the claims for themselves. In the case of the Digha Nikaya this is true to an extent, but only to an extent. Many of the claims about the nature of things (such as the cosmos) are not verifiable by any means other than through appeals to magical thinking, to superhuman powers, faith, or an epistemology that implies a completely different theory of mind, brain and maybe even physical universe.

Commentaries explain that the Digha Nikaya served as "religious propaganda" at the time of its composition, choosing discourses that incorporated ideas of other religions of the time to make Buddhist thought more tangible to listeners. It makes sense that the discourses that were developed were situated in their historical epoch, and that one would be deliberate in crafting engaging stories if the purpose was to convert believers from other religions. Regardless, I found myself being surprised by the extent of what I would call speculative and doctrinally irrelevant statements.

I don't want to imply that this was the main or most important impression that the Digha Nikaya made on me, but I cannot leave it unsaid. The result is simply that there are many portions of the text which I pass by "in silence". There are many ways to approach a text: on the one end of the spectrum one can be critical from the outset, trying to find logical and/or factual errors in as many statements as possible; one the other end one can accept everything that is said without any questioning at all. Neither of these ways of reading are going to bring me closer to achieving my goal of establishing more robust happiness using Buddhist mental tools, so I am deliberately trying to veer away from these two extremes.

I am approaching the text more like going for a walk in the forest: much like I see that there are these organisms, and that I can intentionally relate to them or pass them by, I see in the text that there are these considerations about the way things are. When I encounter ideas that don't resonate with me, arguments which I consider invalid, or empirical statements which are not falsifiable I try not to overreact, as I register them, and continue my search.

Even though it might sound trivial, my expectations were also shaped by all other texts that I had read before. In this sense the Digha Nikaya gave me an encounter with an entirely different type of text. Discourses appear in a numbered sequence of no particular thematic order. Each discourse tells the story of a dialogue between the Buddha and someone else. Sometimes, the dialogue figures one of the most eminent disciples instead of the Buddha himself. The conversation partners vary widely in terms of their role in society, and their knowledge of the Dhamma (the Buddha's teaching). The normal structure is a brief description of the scene, a question is asked, and an explanation follows, sometimes with repeated questions and answers.

The structure of the Digha Nikaya and the discourses themselves are of course an artefact of the writings having their origin in the oral tradition. This accounts for many of the unusual features of the text (in comparison with texts that are written down from the outset). But there is something else that is even more different. The ideas have a very different _feel_ about them. They are almost other-worldly. Or to borrow a Buddhist term, the ideas have a distinct non-worldliness about them. They have a very particular "mental flavour". In my experience, the mental flavour is a result of both _how_ things are being said (the underlying intention, the attitude, the very deliberate and sometimes unusual choice of words) and _what_ is being discussed. Buddhist ideas are unlike anything else I've ever encountered.

The following discourses from the Digha Nikaya stood out to me:

* Sammanaphala Sutta - The Fruits of the Homeless Life
* Potthapada Sutta - States of Consciousness
* Mahanidana Sutta - The Great Discourse on Origination
* Sakkapanha Sutta - Sakka's Questions
* Mahasatipatthana Sutta - The Greater Discourse on the Foundations of Mindfulness
* Sangiti Sutta - The Chanting Together
* Dasuttara Sutta - Expanding Decades

Sometimes a whole discourse resonates with me. Other times it can be a specific paragraph, sentence or phrase that sticks with me. One example from the Mahanidana Sutta: "Ananda, when once a monk attains these eight liberations in forward order, in reverse order, and in forward-and-reverse order, entering them and emerging from them as and when, and for long as he wishes, and has gained by his won super-knowledge here and now both the destruction of the corruptions and the uncorrupted liberation of heart and liberation by wisdom, that monk is called both-ways-liberated, and, Ananda, there is no other way of both-ways-liberation that is more excellent and perfect than this."

The phrase that sticks with me here is: _there is no other way of both-ways-liberation that is more excellent and perfect that this_. What is it that strikes me here? It is the "more excellent and perfect than this" part. That one would systematise ways of being, and their accompanying states of mind in a way that makes it possible to define "both-ways-liberation" is already fascinating. And then to consider the various ways of being in this way, compare them, and pronounce that one specific way is the most _excellent and perfect_ way is just beautiful.

Another example, from the Dasuttara Sutta: "This concentration is both present happiness and productive of future resultant happiness; This concentration is Ariyan and free from worldliness; This concentration is not practised by the unworthy; This concentration is calm and perfect, has attained tranquilisation, has attained unification, and is not instigated, it cannot be denied or prevented; I myself attain this concentration with mindfulness, and emerge from it with mindfulness."

The phrase that resonates most with me here is: _this concentration is calm and perfect_. It is such an amazing way of relating to and regarding your own concentration. Even before doing so, just the fact that one would sit down and make time to concentrate is a beautiful thing to do. In doing so, one does not depend on anything or anyone (in any immediate sense); one does not cause yourself, anyone or anything any harm. It can, therefore, be done without any moral reservations or without any concern for your own current or future well-being. Having done so, if you do reach a point where you can consider the quality of your concentration to be calm and perfect, and then dwell in that, then I say it has been a good day. For many, reaching this would represent a radical change in their lives.

There is a kind of perfection to these phrases, to their underlying intention, and their implementation that remind me of how I feel when I listen to music, and the song reaches its most beautiful moment. Similarly it reminds me of sublime experiences I have in contemplative and immersive movement: in yoga, climbing, and skiing. That is not to say that all these phenomena are the same thing, but an important shared charteristic among them is that they are valuable to me regardless of any logical argument that one could make about them.

It also means that I can incorporate practicing and developing concentration into my life, that there is a primary and direct motivation to do so, and that it can be done regardless of the sometimes unnecessary doctrinal scaffolding that surrounds it. That is not to say that all doctrinal considertions are irrelevant, or that practices are completely separable from considerations about them, but it is more robust and sustainable to establish beneficial practices in primary motivations.

# Majjhima Nikaya - The Middle Length Discourses

The Majjhima Nikaya is quite different from the Digha Nikaya: there is less "scaffolding", the subject matter is discussed more directly. There are still references to religious ideas of the time (Devas, Devadatas, Yakkas) but less so. I mentioned that one of my goals was to investigate meditation as a practice for developing happiness, and that I started reading a book about meditation, only to realise that I was tired of relating to other people's reading of Buddhism, instead of reading "the source" myself. It was therefore interesting to see that the Nikayas are not meditation manuals. That is, even though meditation is discussed often, there are no detailed step-by-step instructions of the form: "sit down, close your eyes, focus on the sensation of your breathing, bring your attention to the present moment".

Buddhist meditation techniques are often classified into three types: samatha, vipassana, and metta, popularly known as concentration, insight, and loving-kindness. The Majjhima Nikaya makes no clear distinction between these as different methods or types of meditation. There are many descriptions of states of meditative absorption (jhanas), and of the various insights that can and should be gained as a result of, or during medition. Relatively speaking, there is very little discussion on metta. The classification and systematisation of meditation techniques that one finds in other literature is not something that was passed along in the oral tradition that resulted in the Sutta Pitaka.

The Majjhima Nikaya is a book of reflection and consideration. It explains, among other things, the core doctrinal elements of Theravada Buddhism, such as the four noble truths, the noble eight-fold path, and dependent origination. It also describes meditative practices, but these descriptions are a part of a more general reflection on the noble eight-fold path: the prescription for how to live if one wants to make an end to suffering (attain Nibbana, or Nirvana as it is more popularly known).

That is also one of the implicit points made by the text: that meditation is only one aspect of many that needs consideration. Due to the interconnectedness of life, it would be futile to try and achieve meditative absorption or insights if the rest of your life remained reckless and chaotic. That's not to say that one shouldn't try to establish a meditation practice if your life is chaotic - trying to do so can be a helpful catalyst for change. The point is just that you cannot expect meditation to be some magical silver bullet that solves everything while you continue to live the rest of your life as you always did. Even if you do have experiences during meditation that lead to insights about the processes governing your own existence, you still have to apply these insights in actual situations if you want to change your life: you have to behave differently, internally and externally.

I marked 35 discourses as ones that stood out to me. Among these 35, the following are my favourites:

* Dvedhavitakka Sutta - Two Kinds of Thought
* Culavedalla Sutta - The Greater Discourse on Ways of Undertaking Things
* Maharahulovada Sutta - The Greater Discourse of Advice to Rahula
* Anenjasappaya Sutta - The Way to the Imperturbable
* Anapanasati Sutta - Mindfulness of Breathing
* Mahasunnata Sutta - The Greater Discourse on Voidness
* Chachakka Sutta - The Six Sets of Six

From the Dvedhavitakka Sutta: "Bhikkhus, whatever a bhikkhu frequently thinks and ponders upon, that will become the inclination of his mind... so too, there was need for me only to be mindful that those states were there."

From the Culavedalla Sutta: "Knowing this, he cultivates things that should be cultivated and does not cultivate things that should not be cultivated, he follows things that should be followed and does not follow things that should not be followed. It is because he does this that unwished for, undesired, disagreeable things diminish for him and wished for, desired, agreeable things increase. Why is that? That is what happens to one who sees."

From the Maharahulovada Sutta: "Rahula, any kind of material form whatsoever, whether past, future, or present, internal or external, gross or subtle, inferior or superior, far or near, all material form should be seen as is actually is with proper wisdom thus: 'This is not mine, this I am not, this is not my self.'"

From the Anenjasappaya Sutta: "'It might not be, and it might not be mine; it will not be, and it will not be mine. What exists, what has come to be, that I am abandoning.' Thus he obtains equanimity. He does not delight in that equanimity, welcome it, or remain clinging to it. Since he does not do so, his consciousness does not become dependent on it and does not cling to it."

Sometimes whole passages that can be quoted with a large degree of coherence and self-containment, such as the examples above, really stick with me. Other times, single phrases stay with me, like "this is identity as far as identity extends", or "And how is mindfulness of breathing developed and cultivated, so that it is of great fruit and great benefit?" These phrases have the ability to create an entire mental space in which I can dwell. Not a single word is superfluous, and not a single word is lacking. The underlying attitude, the intention, the mental flavour, everything about it is absolutely perfect.

# Philosophical detour

It's hard to grasp Buddhism, its practices and attitudes without considering the context in which the practices were framed: being is the result of karma, intentional action, that operates across the span of an individual life, leading to continued existence and suffering, often represented by old-age and death, a timeless cycle called samsara; the only way to stop the cycle of rebirth-and-death is to ensure that birth does not come about; this is done through the destruction of the basis for continued existence; this is accomplished by being in a way that does not involve becoming attached to intentional action (volitional formations), or put another way by not craving continued existence. This is my own summary, which omits various points, and uses my own translation. There may be technical points that can be disputed in my translation but one should not be confused about that fact that the entire point of Buddhism is to achieve Nirvana, the complete extinguishment of continued existence in samsara.

I do not frame things in this way. Astrobiology predicts that the sun will either consume the Earth, or bake it beyond the point where organic life will be possible, in roughly 3 billion years from now. Humans will either go extinct or evolve into a new species due to the operation of evolution. Organic life emerged from inorganic matter, organising into self-replicating systems. Organisms depend on one another and the ecosystems they emerged from for their existence. One person's intentional actions can influence the life of others through the following mechanisms: genetics, epigenetics, behaviour, and the creation of artefacts (physical objects, systems), and culture (shared psycho-physical reality). Such intentional actions may lead to the creation of suffering in the person who formed the intentions, and may also lead to the creation of suffering in other persons, but suffering also originates in the operation of systems that do not have intentions. In an ultimate sense, intentions also originate in low-level physical systems - our solar system, and us, seems to have come from a space cloud made of dust and gas.

To continue the thought experiment in framing, in this way all things are entangled and connected. But I cannot see how one could meaningfully say that beings, or any of their temporal features, are physically reborn as a new organism, such that your intentional actions now have consequences for _you_ after your organism's death. To the extent that _you_ exist at all, you are a spatio-temporal artefact of your organismic substrate. If you take yourself to be your conscious presence, then in a way we are not born at all, we merely arise from the organisms that are evolving and replicating. And if "we" are not born, then we do not die. Sometimes we are present, sometimes not. One could then say that this presence is partially a phenomenon without identity, even though it is rooted in physically and relationally unique organisms. And then one could say that the experience of one is equivalent to the experience of another. What difference does it make, in a global non-personal sense, whether suffering is experienced by me, or another? The difference is spatio-temporal (it is happening somewhere else, rooted in another organism), but it is suffering all the same.

So one could say that making an end to suffering as such, is a project that transcends the experience of a specific individual at the same time that it is rooted in a specific individual. Suffering is _always_ experienced by someone. In this sense, one can think about the relation between your own intentional actions and other people's suffering. If your intentional action leads to their suffering, it is the same as creating suffering for yourself. So if you want to get practical about ending suffering, then you have to stop creating more suffering for yourself, _and others_. In my view this does not include humans only. It seems entirely plausible that other species also have the capacity to experience suffering. So the task expands to having to create a human civilisation, or on a smaller scale, ways of living and relating to other organisms, that does not generate suffering.

I'm not sure if organic life is compatible with such a project, but one can at least try to live in such a way that you do not _intentionally_ create more suffering for yourself or others. And in this sense, reading Buddhist literature is very interesting and relevant, regardless of the difference in framing.

# Reflections on reading

I sometimes think that a good way to summarise Buddhism is that: it has nothing to do with anything, and everything to do with everything. It has nothing to do with anything because it is not concerned with doing anything conventional. It has everything to do with everything because it is concerned with the development of the mind, and without a mind, one cannot really live a human life in any meaningful sense. So while it may not be concerned with anything that one does in conventional life, the way of life that it advocates invariably has an effect on a particular conventional life by way of the the mind. If you want to change your mind, you need to change your life. If you want to change your life, you need to change your mind. What is relevant to me is Buddhism's concern with how one can intervene in this process in such a way that you cease to produce new forms of existential suffering for yourself.

I say _existential suffering_ because I find the notion that Buddhist practices can eradicate _all suffering whatsoever_ for a given individual an exaggeration. And the discussion of the end of suffering in the context of depend origination is ultimately concerned with making an end to existence that spans across many rebirths. Not existing at all seems like a trivial solution to the problems of existence. What _is_ interesting, is how to develop sentient cognitive processes that do not generate new suffering or depend on inflicting suffering. K.R. Norman, in A Philological Approach to Buddhism, translates Dukkha as "pain". Very often it is translated as either suffering or non-satisfactoriness. There is quite a big difference between pain, suffering, and non-satisfactory. So much so, that having one term to encapsulate them risks making the term meaningless. And there are serious problems to the idea that one's own intentions are the cause of _all_ pain, suffering, and non-satisfactory experiences that you have.

To just take one example, consider the prion. A prion is a (sporadic, random) misfolded protein that leads to cellular death, and incurable, progressive and fatal diseases. Can one claim that these proteins are misfolding due to ignorance and volitional formations? I think not. It is also a stretch to say that if you adopt every precept with perfection that you are _guaranteed_ to never again experience any suffering whatsoever. You could be living perfectly and then someone drops a bomb on you, or some natural disaster makes you lose a leg. And to apply it to silly things like everyday bodily pains amounts to a trivialisation of the subject matter. Since dependent origination deals with causal chains that involve the formation of intentions, Dukkha has to refer to experiences of existential hardship that arise due to our own intentional actions. Such experiences of hardship should be taken seriously, they are often the catalyst for behaviours that cause more gross forms of suffering for ourselves and those around us, especially when these behaviours are aggregated across all living humans.

This is what I choose to focus on in the very _specific_ texts that I've read thus far. I stress _specific_ because the actual details of the prescriptions, and the reasons behind them are very specific. Much more specific and different that you can really imagine if you do not look for yourself. In some sense I wonder whether one can paraphrase the ideas into contemporary language, and a contemporary scientific worldview, without altering the ideas too much. To put it in another way, I'm not sure it is possible to arrive at Buddhism as it is expressed in the Sutta Pitaka today. That is, if you were to implement all of the underlying methods that lead Siddharta Gotama to express his teachings _today_, I don't think you would express it in the same way. It might be "equivalent enough", but it would look different. In a way, this is what I am trying to do: to see what underlies the teachings, to understand which questions and processes lead to their articulation, and to then ask these questions and apply these processes to my own life.

My own theory about the large degree of "different-ness" that one encounters in the Sutta Pitaka, and this often comes to mind when I am reading, is that it is partly due to the historical context in which Buddhism was first articulated, and how different that was from the current historical epoch. The "scaffolding" is tied to the language and paradigms of the time, and the practices grew out of the existing religious communities and their practices.

One prime example is the presence of the concept of rebirth, something that is completely alien to contemporary evolutionary biology and modern physics - the paradigms that inform my own understanding of how organisms develop and how the physical universe operates. I sometimes hear people say that this refers to moment-to-moment changes, and other times I see people taking it literally (such as in the commentaries to the suttas). The suttas themselves take up the theme from time to time, justifying the view as a "safe bet" in the face of uncertainty. I think that it was there because the idea was present in the religious communities of the time, and that it was necessary to take _some_ stance on it. But for my own reading I find it to be a distraction, an unnecessary doctrinal element that I'd rather do without. You could say that Nirvana becomes less ultimate if rebirth is not a thing, and that it may remove some of the motivation for adopting the ascetic life (as advocated by Theravada Buddhism). I think that whatever the case may be, whatever the relation between one person's intentional actions and another's experience, making an end to the arising of existential suffering has to happen in a specific individual's life. So the task is no different.

The other historical detail that is present in my mind when I'm reading the texts is that the communities of religious seekers all practiced some form of asceticism. The ascetic practices were an essential part of the methods used to arrive at Buddhism. If you want to observe the effect of one thing on another thing, you have to introduce variation into the process. And one way to see what effect something has is to abandon it altogether, and observe the changes that come about. This is, in fact, a summary of dependent origination: when this is present, that comes to be, when this ceases, that ceases. The wandering ascetics of the time responded to their dysfunctional societies by minimising their involvement in it. Their social analysis, although not articulated explicitly in the Suttas, was that the structure of society supported the development of (and maybe required) notions about the conventional self and its needs that led to the creation of suffering. And that this can be avoided by not participating in the processes of society.

In doing so they turned away from all economic activity in favour of living off gifted food and shelter (when absolutely necessary). In a way they established a new type of economic activity where they "traded" insights and reflections for material goods. There was also the notion of merit-making (supporting the monks would lead to a more favourable rebirth). It is here, and in the particularities for the ascetic practices, that I differ most from the early Buddhists in my response to the world.

The devaluation of food and the body that co-developed with the ascetic experimentation in those times is something that does not resonate with me. My mind is the primary location of my existence (if I have no mind then I do not exist according to myself, however temporal my existence may be, when it is there). My mind depends on my brain, its substrate. My brain is a part of my body, is wholly immersed in it, and fully dependent on it for its functioning. My body needs nutrition, and I get that from food. So I care very deeply about that state of my body, its cultivation, and the food I eat. And what about the food? Where does that come from? From the processing of other organisms, and the environment. So I am trying to get more involved with such processes through foraging and gardening. I think many problems come about when one is alienated from the body, food, and the environment. This alienation is probably what many experienced when societies transitioned from hunter-gatherer tribes to agricultural modes of living, where increased specialisation removed people from being involved in the activities that directly support the well-being of their organisms. The degree of alienation is even more pronounced in our current post-industrial epoch.

Another point which shines through in the more ascetic attitudes and statements in the Sutta pitaka that does not sit well with me, is the idea that the family (and the home life) is inherently problematic. I am a father of two boys, and I have no intention of giving up on my responsibilities to them, ever. In fact, I am trying to use the mental tools that I develop through my reading to be the best father I can be - to be more patient and accepting, to have a more stable emotional base through the direct cultivation of contentedness.

There are, however, many aspects of the ascetic spirit that appeal to me, and many parts of the Buddhist analysis about our underlying tendency to craving that I find very relevant to the problem of living a good life in contemporary society. Oslo is a society of abundance, excess, and decadence. I cannot speak for everyone that lives here, but my own basic needs are met so many times over that it is a moral crime for me to be unhappy about my life. And yet, one can very quickly end up in states of mind that make your own life seem problematic, leading to striving for more things, more consumption, or an almost obsessive and incessant urge to rearrange the state of the world around you to generate novel sources of dopamine. It's not that one should just passively accept the status quo, and stop striving for anything at all, but there are ways of undertaking things, and then there are ways of undertaking things.

Buddhism has succeeded in creating culture based on extremely minimalistic consumption. They have developed practices for the development and cultivation of the mind that do not directly depend on the trading of goods and services. That is, in order to progress with the development of the mind, you do not need to buy anything, or destroy anything. You just need enough energy, and time, to sit yourself down and continue breathing. They have developed ways of relating to other people that are supportive of this effort, with the aim of ceasing the creation of more suffering via obsessive and unnecessary activity. A such, it is a pursuit that can be done with moral calm. By adopting these practices, in the ways that you can and make sense, you are not going to contribute to increasing the already harmful levels of consumption that society is pushing us to keep increasing. It might be that the Thervadins advocated for a lifestyle that does not appeal to me in each and every way, and that they had doctrinal views that I do not exactly share, but they have created many beautiful practices that stand in stark opposition to the utterly useless and sometimes harmful goods and services, and ways of being, that are produced or advocated by current economic systems.

I also really like the spirit of independence that underlies Buddhist ambitions. That they are pursued and realised by each person for their own sake, not depending on others, and not depending on elaborate and fragile social and technological structures. There is something extremely refreshing and almost shocking about the directness of the practices. Want to be more content? Practice being so. Want to stop being angry? Abandon it. Want to be more happy? Cultivate an attitude of joyfulness.

# Applications

It is quite obvious from the reflections that I have a complicated relationship with the Sutta Pitaka. One thing is clear though: my reading inspires reflection and experimentation in my life, and this is what I want. I didn't set out on this project to find a new set of ideas to believe in, or to find rigid rules to shape my life. I'm not interested in beliefs or rules. I'm interested in developing a better understanding of the processes that underlie my own existence, that operate in my life, and how I can intervene in these to create robust and morally sound happiness for myself.

To investigate how you tend to create existential suffering for yourself, and to develop practices for eradicating the underlying tendencies that lead you to do so is a very unusual thing to  pursue in contemporary society. And so I find it quite difficult to talk about this reading project, and how I apply the insights I gain from it, with other people. It is just a very different approach to life than the one that is implicitly or explicitly advocated (and sometimes shoved down your throat) by the global capitalist world we live in. I'll try to identify and describe how this project has shaped my life thus far.

Psychological framing has a big impact on how you experience things. Inspired by the spirit of independence found in the Sutta Pitaka, and motivated by my goal of establishing more robust happiness in my life, I've started practicing a new way of framing my life in general. I try to create a psychological point of departure where I tell myself that I am alright, and that I do not need anything. That given this point of departure, I welcome everything that brings me joy in addition to this, and that I am thankful for it. For example, being able to go skiing, climbing, or cycling are all things that bring me great joy, and that with this framing I engage in them with a spirit of gladness and thankfulness, instead of being desperate for it and thereby being depressed when I cannot do it for some reason. This framing also plays a huge role in how you react to unexpected events, how deep the disappointment goes. As the Maharahulovada Sutta says: "unwished for, disagreeable contacts will not invade your mind and remain". One thing that I aim to do through my meditation practice is to solidify this psychological frame as an inner space characterised by calm and contentedness.

I've recently written about [my dietary experiments](https://leonomics.com/dietary-experiments.html), [my increasing involvement with foraging](https://leonomics.com/foraging.html), and [the my ever-evolving of my yoga practice](https://leonomics.com/twenty-years-of-yoga.html). These are all aspects of life where I practice developing beneficial attitudes, moderation, abandonment, awareness, mindfulness, movement, contemplation, meditation, ways of relating to other organisms, other people, ways of talking, thinking and being together with others. As such, these are areas of life where I deliberately try to apply insights that I gain from reading the Sutta Pitaka, from thinking about it, and from meditating on it. By an large my meditation practice has been structured on the Mahasatipatthana and the Anapanasati Suttas, sometimes on the Anenjasappaya Sutta. I've also been exploring how I can develop ways of meditation that are rooted in and inspired by foraging. This is an ongoing open-ended exploration.

I recently read a fascinating book called The Ideological Brain, by Leor Zmigrod. One of the most interesting findings discussed in the book is that the people's low-level perception influences their higher level thinking. That is, when people tend to have a more rigid approach to basic perceptual and cognitive tasks, such as imagining what an object can be used for, or seeing on which side of a screen an event occurs, they also tend to be more ridig in their ideological worldviews. This made me wonder about whether the cognitive and perceptual experimentation that one encounters in meditation and in ascetic practices can contribute to developing novel world views via the same mechanisms. A big part of engaging with Buddhist ideas, and applying them, involves changing the way you view things, all the way from very low level cognitive states, through perception, and eventually to your world view and approach to life.

It is easy to forget, in the business of everyday life, that much of what you encounter in your mind, such as the language you think with, is a human construct, and has been made up by other people than yourself. In fact, the entire world is constructed. It is a transformation of the raw materials found in the environment around us, and is essentially an amalgamation of mental projections onto matter, creating the context in which you move in space, shaping your perceptions, your memories and the meanings you attach to things. All of this can become very clear in meditation, when you consider the origins of what you encounter while doing so. Why does this matter? The implication is that you don't have to take what you encounter in your mind and in the world as a given, as _necessarily so_. Of course it is real enough to have consequences for your organism, it _is_ not an illusion that you can just ignore, but you can also create your own novel building blocks of experience, meaning, and culture that are not so entangled in the world. In my own life I'm trying to contribute to the creation of wholesome culture in foraging and yoga through teaching and participation. And in my family life, by helping my children develop an independent foundation for agency in the world. Being exposed to the language of the Sutta Pitaka has also given me access to new words, concepts, new ways of thinking, and talking that help me in these pursuits.

I'm skeptical and stubborn by nature, and in this respect the ascetic impulse to abstain from participation, and to completely abandon things, is quite easy for me to adopt. The Sutta Pitaka is full of considerations about the potential (existential) danger of getting involved in things, hence the emphasis on non-attachment, equanimity, and abandonment. What I like about this is the skepticism to the idea that the social systems and practices that one encounters are necessarily benevolent in nature. There is, for example, no guarantee that the political system of the day is one that will enable you to thrive personally. Similarly, and this is especially relevant today, there is no guarantee that any given digital system that you interact with has been designed (or evolved) with your benefit in mind. The attention economy wants to maximise keeping your attention by any means necessary, regardless of the content, and regardless of the effect that it has on you. My relation to digital systems has been another area of experimentation where I am applying ascetic practices, to observe the effects of not engaging, and to free up time and mental resources to be able to direct my attention to other things, such as reading the Sutta Pitaka!

# In closing

These reflections and applications are not presented here as final or exhaustive, as prescriptions or suggestions, but they are an accurate enough representation of what reading the Sutta Pitaka has been like thus far. At the time of writing I'm busy reading the Samyutta Nikaya. After that, both the Anguttara and Khuddaka Nikaya remain.
