
---
title: "Six years in Norway"
date: "`r Sys.Date()`"
output:
    tufte::tufte_html: default
---

```{r setup, include=FALSE}
library(tufte)
knitr::opts_chunk$set(tidy = FALSE, cache.extra = packageVersion('tufte'))
options(htmltools.dir.version = FALSE)
home <- Sys.getenv("HOME")
```

I arrived in Norway on the 20th of April 2012 with the aim of staying for at least 5 years. I figured you need at least 5 years to make such a huge move worthwhile - it would be enough time to learn the language, get a proper job, make friends and feel at home in the culture. I left South Africa with cash in hand, moved in with my girlfriend, and started looking for a job in Norway. Alongside this I was doing two consulting jobs as an economist: one for an NGO in Norway and another for the Department of Energy in South Africa.

The short story is that I got a job quite quickly as a data analyst at a Norwegian telecommunications company, Telenor. I worked there for 3 years after which I took a job as a software engineer at the University of Oslo's Center for IT. There I am group leader for Research Services working mostly with sensitive data. I'm almost fluent in Norwegian, we own a flat, have a cat, and a son. I guess you could say I'm an _integrated_ immigrant. Anyways, I thought it was time to reflect more systematically about certain aspects of the journey.

## Meta

I have actually been trying to write this post for more than a year. It started off with the title, "Five years in Norway". I gave up on it because even though I could say many things about the last six years, I find it difficult not to generate clichés. So at the risk of doing so, I'm going to try to commit something to writing and be done with it.

## Norwegian

Learning a new language is an adventure - especially learning to live in that language. I had a number of advantages that set me up for a good learning path. 1) Having two Germanic languages, Afrikaans and English, as background for Norwegian is a good start. One can recognise many words to begin with. 2) My girlfriend is Norwegian, so I can ask for help at home. 3) I found a job where I was not required to speak Norwegian, so I had plenty of time to learn, and 4) I made Norwegian friends who helped me by refusing to speak English to me, even though I would speak English to them.

To speed up learning I met with people before work, practicing having conversations, reading out loud to learn pronounciation and increase my vocabulary, and later on did some informal writing exercises. After that I took a week-long intensive course at a community college, and wrote a test to certify my competence. In passing the test I have evidence that my Norwegian is good enough to enroll for University, and it allowed me to obtain permanent residence. At my current job I speak Norwegian about 30% of the time.

Of course one is never finished learning a language: there are always new challenges popping up, new situations in which you suddenly find you lack the vocabulary to express yourself. And the extent to which you can immerse yourself in a language, and its cultural artefacts, is endless. So the journey is far from over.

## Identity

I often joke at home that I am a traitor to my home country, to my mother tongue, and to my culture. While I don't really think this is true, there is a certain amount of tension in me, about my relationship to South Africa, Afrikaans, and my original culture.

When I say that I am losing my identity, also half joking, some people tell me that rather than losing one I am gaining another. But I'm not so sure. When you don't live in a country, you are not surrounded by the people, you do not speak the language, you do not experience the collective events. In short, you fall out of the psyche of the country and the culture. I do not live in a diaspora community either, so there is no community of South Africans around me keeping the everyday reality of the country and the culture alive. While I am not completely disconnected (I visit for more than a month every year, read news, speak to friends and family) I can feel myself losing touch with the reality of the country. And when I am there I notice that I sometimes struggle to complete my sentences in Afrikaans without hesitation. Disconcerting.

None of this makes me a _traitor_, but I think there is some truth to the statement that I am losing a part of my identity. And it is also true that I am gaining new parts, this is only natural. But what frustrates me sometimes is that it is quite a lonely identity: 2/3 South African, 1/3 Norwegian?

I think all immigrants face this challenge: the more you integrate the more you sacrifice from your old identity. After a while it can sometimes feel like you are stuck in the middle: not quite Norwegian, not quite South African either.
This is not science though, these are just feelings I have from time to time, and it is not obvious to me what to do with them.

## Landscape

Norway is a beautiful country, with wild mountains, fjords, forests, glaciers, and an incredibly dense and complex coastline. When I first came to Norway on holiday in 2010, I went BASE jumping at Kjerag, at Lysefjorden, and was completely awestruck by the spectacular landscape. Having lived here for six years now, I have had many opportunities to experience different parts of the country, and be immersed in the landscape. Some places worth mentioning are: the Jotunheimen mountain range, Vega, Lofoten, Senja, the Lygen Alps - all places where I went either hiking, climbing or skiing.

Doing things you love, and spending time in nature helps you to build a connection to the landscape, both mental and emotional. Revisiting areas awaken old emotions and associations, and being engaged in outdoor sports means that these associations are positive and uplifting. In this way the landscape of a place becomes an integral part of who you are, and your happiness in a place (at least for me).

It has taken a very long time to develop a deeper connection to the Norwegian landscape, to feel at home in it. To some extent I still do not feel at home in it, especially when I compare it to my home mountains in South Africa. Since my childhood was spent in the mountains of South Africa, it is only natural that I feel a stronger affinity to the mountains there.

## Politics

The most salient feature of European politics today is the immigration debate. This debate, and the reality of immigration from other parts of the world, will intensify in the future. If climate change pans out in the way that the UN is predicting, then more people will want to live in the North.

Many Northerners react negatively to the influx of immigrants, whether they are economic migrants or refugees. This is usually due to being scared of economic and/or social change - especially when the immigrants have Islamic cultural roots. Some are positive to change. Others have well-founded skepticism. Yet others react in blatantly racist ways. It is a tense debate.

I try to maintain both a long term historical perspective and practical outlook to this situation. The way I see it, Europe made itself rich by exploiting resources and societies all over the world for hundreds of years, leaving behind it a trail of social chaos (not _just_ chaos I know, there was order too). Anyway, now Europe is experiencing some pressure in the opposite direction. Yes it might be difficult to deal with social change, and yes it might be unfair that the current generation has to pay for the sins of their fathers, but the Northerners have enough smart people and resources to solve this. I think the best strategy is to gear up for the coming challenge instead of wishing it away.

## 10450.62 km

Living so far away from your family is not great. Skype, while useful, just doesn't have the ability to replicate the intimacy of being in someone's physical presence while speaking to them. Sure I am just two flights away, and I journey to South Africa at least twice a year, but the thing I miss most is the low-threshold interaction, the feeling of being in the same place.

The importance of low-threshold interaction becomes even more visible when you have children. Being able to share small things is what adds up to sharing a life. I hope to find a way to spend more time in South Africa in the future.

## The social contract

Before moving to Norway I had lived most of my life in South Africa. In South Africa, citizens have a tenuous relationship with the state. My own expectations of the South African state can be summed up as follows: "please leave us alone so we can take care of ourselves". Suffice it to say that the history of the country, both before and after Apartheid does not engender confidence in the ability of the state to deliver quality public services to the majority of people.

In this regard coming to Norway was quite a shock: here people actually have high expectations about the quality of public services, and high levels of political engagement across a broad socio-economic spectrum. Having been the recipient of quality public services for years now has fundamentally changed my views on the ability of the state to deliver public services.

## Women in society

Norway, like other Nordic countries, has done well to remove barriers for women to pursue their goals in society. This is a very big topic, but I am just going to note that living here has increased my awareness about how societies treat different genders differently in structural ways, and how social conduct and codes often put women at an unfair disadvantage. I am very thankful for this increased awareness.

## In closing

If someone had told me in 2010, when I first came to Norway on holiday, that I would now be living here, owning a flat, have a family, and speak the language, I would have found it difficult to believe. I wonder where I'll be six years from now.
