
---
title: "Why I work"
date: "`r Sys.Date()`"
output:
    tufte::tufte_html: default
---

```{r setup, include=FALSE}
library(tufte)
knitr::opts_chunk$set(tidy = FALSE, cache.extra = packageVersion('tufte'))
options(htmltools.dir.version = FALSE)
home <- Sys.getenv("HOME")
```

I often get contacted by recruiters notifying me about job opportunities. The majority of the time the opportunities fit my skills, but not with my personal motivation to work. This text is a reference that will help others understand why I work, and therefore which opportunities are interesting to me.

## Meaning

My work has to be meaningful to me. This implies that it has to fit with my values, ethics, and ideals. The most succinct way to summarise what these aspects are, is to simply say that I want my work to make the world a better place. Any company or institution that does not have a substantial goal of making a positive contribution to society, or solving an important problem, is not worth considering. Making the world a a better place is of course a difficult task, and it is not exactly clear what it means, but it should be possible to have an intelligent conversation about how your work is involved in this task.

## Intellectual challenge

I need difficult intellectual challenges to be happy. Without them I feel like my brain is going to waste. What I enjoy is to solve practical problems using abstract thinking. Jobs where I am engaged in this process generate sustainable internal motivation for me.

## People

I do not like working alone, even though I am capable of doing it when required. I believe that working in teams allow people to produce work that is beyond their individual skill levels.

## Health

Even if I had enough money to never work again, I would still work. Meeting people who are different from you, and solving problems together keeps you healthy and balanced.

## Money

I most certainly want to earn enough money. But without the other aspects, a well-paying job is not sustainable.
